---

- name: Ensure this is a VirtualBox guest
  fail:
    msg: "Not running inside a VirtualBox guest"
  when: ansible_virtualization_type != "virtualbox" or ansible_virtualization_role != "guest"

- name: Install packages required to build VirtualBox Guest Additions
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - bzip2
    - gcc
    - kernel-devel
    - net-tools

- name: Mount VirtualBox Guest Additions ISO
  mount:
    name: /mnt
    src: "{{ ansible_env.HOME }}/VBoxGuestAdditions_{{ lookup('file', vbox_version_file) }}.iso"
    fstype: iso9660
    opts: loop
    state: mounted

- name: Run VirtualBox Guest Additions installer
  shell: sh /mnt/VBoxLinuxAdditions.run
  failed_when: false

- name: Unmount VirtualBox Guest Additions ISO
  mount:
    name: /mnt
    src: "{{ ansible_env.HOME }}/VBoxGuestAdditions_{{ lookup('file', vbox_version_file) }}.iso"
    fstype: iso9660
    opts: loop
    state: unmounted

